# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
 
#---------------------------------#
#      general configuration      #
#---------------------------------#
 
# version format
version: 1.3.0.{build}
 
# branches to build
branches:
  # whitelist
  only:
    - master
 
# Do not build on tags (GitHub only)
skip_tags: true

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several configurations to build matrix:
configuration:
  - Debug
  - Release

environment:
  matrix:
    - solution_name: Source\PayPal.SDK.NET40.sln
    - solution_name: Source\PayPal.SDK.NET45.sln
    - solution_name: Source\PayPal.SDK.NET451.sln

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: msbuild %solution_name% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests from different categories as separate jobs in parallel
test:
  categories:
    - Unit
